import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { Finding, RoeSpec, SessionState, ToolRunResult } from "./types";
import { appendWork } from "./session_state";
import { isInScope, candidate } from "./scope";
import { makeFinding } from "./finding_types";

export async function inferPhase(dir: string, phase: number, roe: RoeSpec, session: SessionState, results: ToolRunResult[], llmInference?: string) {
  const findings: Finding[] = [];
  const parsedLlm = parseJsonObject(llmInference);
  for (const c of parsedLlm?.candidates ?? []) {
    if (c.host && !session.candidates.some((x) => x.host === String(c.host).toLowerCase())) session.candidates.push(candidate(String(c.host), "llm-inference", String(c.reason ?? "LLM candidate")));
  }
  for (const lf of parsedLlm?.findings ?? []) {
    if (lf.title && lf.severity && lf.evidence) findings.push(makeFinding(session.findings_index.length + findings.length + 1, { title: String(lf.title), severity: lf.severity, category: String(lf.category ?? "LLM inferred"), affected: array(lf.affected), impact: String(lf.impact ?? "See evidence."), evidence: array(lf.evidence), reproduction: array(lf.reproduction), remediation: String(lf.remediation ?? "Review and remediate the vulnerable control."), references: array(lf.references), redaction_notes: "Generated by LLM inference from normalized output; verify before final delivery." }));
  }
  for (const r of results) {
    const text = JSON.stringify(r.result ?? {}).toLowerCase();
    for (const sub of r.result?.subdomains ?? []) {
      const host = String(sub).toLowerCase();
      if (isInScope(host, roe) && !session.candidates.some((c) => c.host === host)) session.candidates.push(candidate(host, r.outDir, "in-scope subdomain discovered; requires approval before active probing"));
    }
    for (const host of extractHosts(text)) if (!session.candidates.some((c) => c.host === host)) session.candidates.push(candidate(host, r.outDir, isInScope(host, roe) ? "in-scope URL/redirect discovered; requires approval before active probing" : "different-host URL/redirect discovered; not probed unless later scoped and approved"));
    if (phase === 2 && /(mongodb|redis|elasticsearch|memcached|kubernetes|docker daemon|2375|6443)/.test(text)) findings.push(makeFinding(session.findings_index.length + findings.length + 1, { title: "Potential exposed sensitive infrastructure", severity: "HIGH", category: "Exposed infrastructure", affected: affectedFromResult(r), impact: "A reachable administrative or datastore service may expose sensitive data or control-plane access if unauthenticated.", evidence: [r.outDir], reproduction: ["Review normalized result.json and validate with a single non-invasive request only."], remediation: "Restrict administrative/datastore services to private networks or VPN; require authentication; remove public listeners.", references: ["OWASP API Security Top 10: Security Misconfiguration"], redaction_notes: "Raw output is redacted by the runner." }));
    if (phase === 7 && /access-control-allow-origin[^}]+attacker\.example\.org/.test(text) && /access-control-allow-credentials[^}]+true/.test(text)) findings.push(makeFinding(session.findings_index.length + findings.length + 1, { title: "Credentialed CORS origin reflection", severity: "HIGH", category: "CORS", affected: affectedFromResult(r), impact: "A malicious website may read authenticated browser responses if cookies or HTTP auth are used.", evidence: [r.outDir], reproduction: ["Send Origin: https://attacker.example.org and observe reflected ACAO with ACAC true."], remediation: "Use an exact allowlist for trusted origins and avoid credentialed wildcard/reflected CORS.", references: ["OWASP CORS Misconfiguration"], redaction_notes: "No response bodies retained unless needed for proof." }));
    if (phase === 12 && /(x-powered-by|server)/.test(text)) findings.push(makeFinding(session.findings_index.length + findings.length + 1, { title: "Verbose technology disclosure headers", severity: "LOW", category: "Information disclosure", affected: affectedFromResult(r), impact: "Verbose headers aid fingerprinting and targeted vulnerability research.", evidence: [r.outDir], reproduction: ["Inspect response headers in result.json."], remediation: "Remove unnecessary Server and X-Powered-By headers at application/proxy layers.", references: ["OWASP Secure Headers Project"] }));
  }
  for (const f of findings) { const rel = `findings/${f.id}.json`; await writeFile(join(dir, rel), JSON.stringify(f, null, 2)); session.findings_index.push(rel); await appendWork(dir, `\n## ${new Date().toISOString()} — Finding created: ${f.id}\n- Severity: ${f.severity}\n- Category: ${f.category}\n- Evidence: ${rel}\n`); }
  return findings;
}
function parseJsonObject(s?: string) { if (!s) return undefined; try { return JSON.parse(s.replace(/^```json\s*|```$/g, "")); } catch { return undefined; } }
function array(v: any) { return Array.isArray(v) ? v.map(String) : v ? [String(v)] : []; }
function extractHosts(text: string) { return Array.from(new Set(Array.from(text.matchAll(/https?:\/\/([a-z0-9.-]+)(?::\d+)?/g)).map((m) => m[1]))); }
function affectedFromResult(r: ToolRunResult) { const v = r.result?.url || r.result?.host || r.result?.domain || r.tool; return [String(v)]; }
export async function readFindings(dir: string, session: SessionState) { const out: Finding[] = []; for (const rel of session.findings_index) try { out.push(JSON.parse(await readFile(join(dir, rel), "utf8"))); } catch {} return out; }
