import { existsSync } from "node:fs";
import { join } from "node:path";
import { RoeSpec, SessionState, PhaseDef, ToolInvocation, PhaseStatus } from "./types";
import { approvedHosts, baseDomains, isInScope, pathAllowed } from "./scope";
import { writeList } from "./tool_runner";
import { rt_whois } from "../tools/rt_whois";
import { rt_amass_passive, rt_crtsh, rt_subdomain_enum, rt_subfinder } from "../tools/rt_subdomain_enum";
import { rt_dns_brute, rt_dns_resolve } from "../tools/rt_dns_resolve";
import { rt_httpx_probe } from "../tools/rt_httpx_probe";
import { rt_port_scan } from "../tools/rt_port_scan";
import { rt_content_discover } from "../tools/rt_content_discover";
import { rt_js_analyze } from "../tools/rt_js_analyze";
import { rt_nuclei_scan } from "../tools/rt_nuclei_scan";
import { rt_auth_bypass, rt_auth_diff } from "../tools/rt_auth_diff";
import { rt_cors_test } from "../tools/rt_cors_test";
import { rt_tls_audit } from "../tools/rt_tls_audit";
import { rt_rate_limit_probe } from "../tools/rt_rate_limit_probe";
import { rt_report_gen } from "../tools/rt_report_gen";
import { rt_breach_check, rt_gau, rt_headers, rt_k8s_probe, rt_shodan_query, rt_third_party_mx, rt_third_party_txt, rt_wayback, rt_wappalyzer, rt_whatweb } from "../tools/rt_misc";
import { rt_api_spec_find, rt_ato_test, rt_authed_content_discover, rt_business_logic, rt_injection_test, rt_jwt_analyze, rt_no_applicable_targets, rt_session_capture, rt_ssrf_test, rt_xss_test } from "../tools/rt_specialized";

export const PHASES: PhaseDef[] = [
 { id: 1, name: "Passive Reconnaissance", requiredAction: "passive_recon", dependencies: [], accountRequirement: "none", skill: "phases/01-passive-recon.md", steps: ["WHOIS", "Passive DNS/subdomains", "ASN/Shodan", "Archived URLs", "Breach checks", "Third-party inventory"], plan: planPassive },
 { id: 2, name: "Active Reconnaissance", requiredAction: "active_recon", dependencies: [1], accountRequirement: "none", skill: "phases/02-active-recon.md", steps: ["Resolve/probe", "DNS brute", "Port scan", "Fingerprint", "Content discovery", "Takeover", "JS analysis"], plan: planActive },
 { id: 3, name: "Authenticated Surface Mapping", requiredAction: "authenticated_testing", dependencies: [2], accountRequirement: ">=1", skill: "phases/03-auth-mapping.md", steps: ["Session capture", "Authed discovery", "API spec discovery"], plan: planAuthenticated },
 { id: 4, name: "Vulnerability Scanning", requiredAction: "vulnerability_scanning", dependencies: [2], accountRequirement: "none", skill: "phases/04-vuln-scanning.md", steps: ["Nuclei baseline", "CVE validation queue"], plan: planVuln },
 { id: 5, name: "Authorization Testing", requiredAction: "authenticated_testing", dependencies: [3], accountRequirement: ">=2-standard", skill: "phases/05-authz-testing.md", steps: ["Two-account diff", "BOLA/IDOR", "Function auth", "Bypasses", "ATO"], plan: planAuthz },
 { id: 6, name: "Injection Testing", requiredAction: "injection_testing", dependencies: [3], accountRequirement: ">=1", skill: "phases/06-injection.md", steps: ["XSS", "SQLi", "SSRF", "SSTI/XXE/deserialization candidates"], plan: planInjection },
 { id: 7, name: "Transport/CORS", requiredAction: "active_recon", dependencies: [2], accountRequirement: "none", skill: "phases/07-transport-cors.md", steps: ["CORS", "TLS", "Smuggling/cache candidates"], plan: planTransport },
 { id: 8, name: "Cloud/Infra", requiredAction: "cloud_testing", dependencies: [2], accountRequirement: "none", skill: "phases/08-cloud-infra.md", steps: ["Kubernetes/container exposure", "Metadata only via SSRF"], plan: planCloud },
 { id: 9, name: "Business Logic", requiredAction: "authenticated_testing", dependencies: [3], accountRequirement: ">=1", skill: "phases/09-business-logic.md", steps: ["Quota bypass", "Race", "Mass assignment", "Webhook abuse"], plan: async () => [rt_business_logic()] },
 { id: 10, name: "Third-party Integrations", requiredAction: "third_party_testing", dependencies: [1], accountRequirement: "none", skill: "phases/10-third-party.md", steps: ["OAuth/OIDC", "Billing", "Analytics", "Status pages"], plan: planThirdParty },
 { id: 11, name: "Admin Panels", requiredAction: "authenticated_testing", dependencies: [3], accountRequirement: ">=1", skill: "phases/11-admin-panels.md", steps: ["Probe approved admin-like hosts only", "Bypass queue"], plan: planAdminPanels },
 { id: 12, name: "Headers/Cookies", requiredAction: "active_recon", dependencies: [2], accountRequirement: "none", skill: "phases/12-headers-cookies.md", steps: ["Headers", "Cookie attributes", "Cache control"], plan: planHeaders },
 { id: 13, name: "Rate Limiting", requiredAction: "rate_limit_testing", dependencies: [3], accountRequirement: ">=1", skill: "phases/13-rate-limiting.md", steps: ["Single safe threshold seed", "Manual escalation within RoE"], plan: planRateLimit },
 { id: 14, name: "Reporting", dependencies: [], accountRequirement: "none", skill: "phases/14-reporting.md", steps: ["Generate markdown report", "Coverage metrics"], plan: async () => [rt_report_gen()] },
];
export function checkGate(phase: PhaseDef, roe: RoeSpec, session: SessionState): { status: PhaseStatus; note: string } | undefined { if (phase.requiredAction && !roe.allowed_actions.includes(phase.requiredAction)) return { status: "SKIPPED_BY_ROE", note: `required action ${phase.requiredAction} absent` }; for (const dep of phase.dependencies) { const st = session.phases[String(dep)]?.status; if (st !== "COMPLETE" && st !== "COMPLETE_WITH_WARNINGS") return { status: "BLOCKED_DEPENDENCY_PHASE_N", note: `phase ${dep} is ${st ?? "unknown"}` }; } const accounts = Object.entries(roe.accounts ?? {}); const needed = phase.accountRequirement === ">=2-standard" ? accounts.filter(([, a]) => a.role === "standard") : phase.accountRequirement === ">=1" ? accounts.slice(0, 1) : []; if (phase.accountRequirement === ">=1" && accounts.length < 1) return { status: "BLOCKED_MISSING_PEER_ACCOUNTS", note: "at least one account required" }; if (phase.accountRequirement === ">=2-standard" && needed.length < 2) return { status: "BLOCKED_MISSING_PEER_ACCOUNTS", note: "at least two standard accounts required" }; const missing = needed.flatMap(([, a]) => a.secret_ref?.startsWith("env:") && !process.env[a.secret_ref.slice(4)] ? [a.secret_ref] : []); if (missing.length) return { status: "BLOCKED_MISSING_SECRET", note: `missing env secrets for required accounts: ${missing.join(", ")}` }; }
async function planPassive(roe: RoeSpec): Promise<ToolInvocation[]> { return baseDomains(roe).flatMap((domain) => [rt_whois(domain), rt_subdomain_enum(domain), rt_crtsh(domain), rt_subfinder(domain), rt_amass_passive(domain), rt_shodan_query(domain), rt_wayback(domain), rt_gau(domain), rt_breach_check(domain), rt_third_party_txt(domain), rt_third_party_mx(domain)]); }
async function planActive(roe: RoeSpec, session: SessionState, dir: string) { const hosts = await approvedHosts(roe, session, dir); if (!hosts.length) return [rt_no_applicable_targets("rt_active_recon", "No approved in-scope hosts; wildcard-only scope requires passive discoveries and explicit approval first")]; const targetFile = await writeList(dir, "outputs/phase-2/targets.txt", hosts); const tools: ToolInvocation[] = [rt_dns_resolve(targetFile, hosts), rt_httpx_probe(targetFile, hosts), rt_dns_brute(baseDomains(roe)[0]), rt_port_scan(hosts.slice(0, 20)), ...hosts.slice(0, 20).flatMap((h) => [rt_whatweb(`https://${h}`), rt_wappalyzer(`https://${h}`)])]; for (const h of hosts) if (pathAllowed("/", roe)) tools.push(rt_content_discover(`https://${h}`, roe.exclusions.paths), rt_js_analyze(`https://${h}`)); return tools; }
async function planAuthenticated(roe: RoeSpec, session: SessionState, dir: string) { const names = Object.keys(roe.accounts).slice(0, 1); const hosts = await approvedHosts(roe, session, dir); return names.flatMap((name) => { const tokenEnv = `REDTEAM_${name.toUpperCase()}_TOKEN`; return [rt_session_capture(name, tokenEnv), ...hosts.slice(0, 10).flatMap((h) => [rt_api_spec_find(`https://${h}`), rt_authed_content_discover(`https://${h}`, tokenEnv, roe.exclusions.paths)]), rt_jwt_analyze(tokenEnv)]; }); }
async function planVuln(roe: RoeSpec, session: SessionState, dir: string) { const hosts = await approvedHosts(roe, session, dir); const urls = hosts.map((h) => `https://${h}`); return [rt_nuclei_scan(await writeList(dir, "outputs/phase-4/live_targets.txt", urls), urls)]; }
async function planAuthz(roe: RoeSpec, session: SessionState, dir: string) { const standards = Object.entries(roe.accounts).filter(([, a]) => a.role === "standard").slice(0, 2).map(([n]) => n); const endpointFile = firstExisting(dir, ["outputs/phase-3/endpoints.txt", "auth/endpoints.txt", "endpoints.txt"]); const tokenA = standards[0] ? `REDTEAM_${standards[0].toUpperCase()}_TOKEN` : undefined; const tokenB = standards[1] ? `REDTEAM_${standards[1].toUpperCase()}_TOKEN` : undefined; const baseUrl = process.env.REDTEAM_BASE_URL; return [rt_auth_diff(standards, endpointFile, tokenA && process.env[tokenA] ? tokenA : undefined, tokenB && process.env[tokenB] ? tokenB : undefined), rt_auth_bypass(endpointFile, tokenA && process.env[tokenA] ? tokenA : undefined), rt_ato_test(tokenA, tokenB, baseUrl)]; }
async function planInjection(_roe: RoeSpec, session: SessionState, dir: string) { const hosts = await approvedHosts(_roe, session, dir); const requestFile = firstExisting(dir, ["outputs/phase-3/request.txt", "auth/request.txt", "request.txt"]); const ssrfEndpoint = process.env.REDTEAM_SSRF_ENDPOINT; const callback = process.env.REDTEAM_CALLBACK_URL; const xssUrl = process.env.REDTEAM_XSS_URL; return hosts.slice(0, 5).flatMap(() => [rt_injection_test(requestFile), rt_ssrf_test(ssrfEndpoint, callback), rt_xss_test(xssUrl)]); }
async function planTransport(roe: RoeSpec, session: SessionState, dir: string) { const hosts = await approvedHosts(roe, session, dir); return hosts.slice(0, 10).flatMap((h) => [pathAllowed("/", roe) ? rt_cors_test(`https://${h}/`) : rt_no_applicable_targets("rt_cors_test", "root path excluded"), rt_tls_audit(h)]); }
async function planCloud(roe: RoeSpec, session: SessionState, dir: string) { const hosts = await approvedHosts(roe, session, dir); return hosts.slice(0, 10).map(rt_k8s_probe); }
async function planThirdParty(roe: RoeSpec, session: SessionState, dir: string) { const directRoots = roe.targets.domains.filter((d) => !d.startsWith("*.")); const hosts = await approvedHosts(roe, session, dir); return [...directRoots.flatMap((d) => [rt_third_party_txt(d), rt_third_party_mx(d)]), ...hosts.slice(0, 10).map((h) => rt_headers(`https://${h}/`))]; }
async function planAdminPanels(roe: RoeSpec, session: SessionState, dir: string) { const hosts = (await approvedHosts(roe, session, dir)).filter((h) => /(admin|internal|staff|grafana|kibana|jenkins|airflow|argocd|vault|consul)/.test(h)); return hosts.length ? hosts.map((h) => rt_headers(`https://${h}/`)) : [rt_no_applicable_targets("rt_admin_panel_probe", "No already-approved in-scope admin-like hosts. The planner does not fabricate admin.<domain> unless discovered/approved.")]; }
async function planHeaders(roe: RoeSpec, session: SessionState, dir: string) { if (!pathAllowed("/", roe)) return [rt_no_applicable_targets("rt_header_audit", "root path excluded")]; return (await approvedHosts(roe, session, dir)).slice(0, 20).map((h) => rt_headers(`https://${h}/`)); }
async function planRateLimit(roe: RoeSpec, session: SessionState, dir: string) { if (!pathAllowed("/", roe)) return [rt_no_applicable_targets("rt_rate_limit_probe", "root path excluded")]; return (await approvedHosts(roe, session, dir)).slice(0, 3).map((h) => rt_rate_limit_probe(`https://${h}/`)); }
function firstExisting(dir: string, rels: string[]) { return rels.map((r) => join(dir, r)).find((p) => existsSync(p)); }
