import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { RoeSpec, SessionState, Severity } from "./types";
import { readFindings } from "./inference";
import { severityRank } from "./finding_types";
import { llmReportReview } from "./llm";
const severities: Severity[] = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];
export async function generateReport(dir: string, roe: RoeSpec, session: SessionState, output?: string, llmCtx?: any) {
  const findings = (await readFindings(dir, session)).sort((a, b) => severityRank(b.severity) - severityRank(a.severity));
  const workTail = await readFile(join(dir, "work.md"), "utf8").catch(() => "");
  const metrics = coverageMetrics(session);
  let report = `# Security Assessment Report: ${roe.assessment_name}\n\nDate: ${new Date().toISOString()}\nSession: ${session.session_id}\nScope: ${roe.targets.domains.join(", ")}\nExcluded domains: ${roe.exclusions.domains.join(", ") || "None"}\nExcluded paths: ${roe.exclusions.paths.join(", ") || "None"}\n\n## Executive Summary\n\nThe assessment executed RoE-gated phases using deterministic TypeScript wrappers and LLM-assisted planning/inference. ${findings.length} verified/potential findings were recorded from normalized evidence. Blocked/skipped phases are represented as coverage gaps, not as tested controls.\n\n## Coverage Metrics\n\n- Terminal phases: ${metrics.terminal}/${metrics.total}\n- Complete or warning phases: ${metrics.complete}/${metrics.total}\n- Skipped by RoE: ${metrics.skipped}\n- Blocked: ${metrics.blocked}\n- Wrapper executions indexed: ${session.output_index.length}\n- Candidate targets not probed: ${session.candidates.filter((c) => !c.approved).length}\n- Raw output retained: ${session.output_index.filter((o) => o.raw_retained).length}\n\n## Phase Coverage\n\n${Object.entries(session.phases).map(([id, p]) => `- Phase ${id}: ${p.status}${p.notes?.length ? ` — ${p.notes[0]}` : ""}`).join("\n")}\n\n## Findings\n\n${severities.map((sev) => section(sev, findings.filter((f) => f.severity === sev))).join("\n\n")}\n\n## Candidate Targets Not Probed\n\n${session.candidates.length ? session.candidates.map((c) => `- ${c.host} (${c.reason}) source=${c.source} approved=${c.approved}`).join("\n") : "- None recorded"}\n\n## Coverage Gaps and Limitations\n\n${coverageGaps(session)}\n\n## Methodology\n\nThe workflow follows passive recon, active recon, authenticated mapping, vulnerability scanning, authorization testing, injection, transport/CORS, cloud/infra, business logic, third-party, admin panel, headers/cookies, rate-limit, and reporting phases. Runtime-discovered different-host URLs are candidate targets only. Raw outputs are replaced after normalized parsing by default to support zero-retention; result.json and redacted audit references are retained.\n\n## Appendix: Output Index\n\n${session.output_index.map((o) => `- Phase ${o.phase} ${o.tool}: ${o.success ? "success" : "warning/fail"}; ${o.dir}; raw_retained=${o.raw_retained}; ${o.summary}`).join("\n")}\n\n## Appendix: Audit Log Tail\n\n\`\`\`\n${workTail.split(/\n/).slice(-120).join("\n")}\n\`\`\`\n`;
  const review = await llmReportReview(llmCtx, report);
  if (review) report += `\n## LLM Editorial Review\n\n${review}\n`;
  const path = output ?? join(dir, "reports", `report-${new Date().toISOString().replace(/[:.]/g, "")}.md`);
  await mkdir(dirname(path), { recursive: true }); await writeFile(path, report); return path;
}
function section(sev: Severity, fs: any[]) { return `### ${sev}\n${fs.length ? fs.map((f) => `#### ${f.id}: ${f.title}\n- **Category:** ${f.category}\n- **Affected:** ${f.affected.join(", ")}\n- **Impact:** ${f.impact}\n- **Evidence:** ${f.evidence.join(", ")}\n- **Reproduction:** ${f.reproduction.join("; ")}\n- **Remediation:** ${f.remediation}\n- **References:** ${f.references.join(", ")}\n- **Redaction:** ${f.redaction_notes ?? "Sensitive values redacted"}`).join("\n\n") : "- None recorded"}`; }
function coverageMetrics(session: SessionState) { const vals = Object.values(session.phases); const terminal = vals.filter((p) => p.status !== "pending" && p.status !== "running").length; const complete = vals.filter((p) => p.status === "COMPLETE" || p.status === "COMPLETE_WITH_WARNINGS").length; const skipped = vals.filter((p) => p.status === "SKIPPED_BY_ROE").length; const blocked = vals.filter((p) => String(p.status).startsWith("BLOCKED")).length; return { total: vals.length, terminal, complete, skipped, blocked }; }
function coverageGaps(session: SessionState) { const gaps = Object.entries(session.phases).filter(([, p]) => p.status !== "COMPLETE").map(([id, p]) => `- Phase ${id}: ${p.status}${p.notes?.[0] ? ` — ${p.notes[0]}` : ""}`); return gaps.length ? gaps.join("\n") : "- No phase coverage gaps recorded."; }
