import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { ToolInvocation, ToolRunResult } from "./types";
import { redact } from "./parsers";

export function tool(name: string, binary: string, args: string[], input: Record<string, unknown>, parser?: ToolInvocation["parser"], opts: Partial<ToolInvocation> = {}): ToolInvocation { return { name, command: binary, args, requiredBinary: binary, input, parser, timeoutMs: 120000, redactRawAfterParse: true, ...opts }; }
export function tsTool(name: string, input: Record<string, unknown>, execute: ToolInvocation["execute"]): ToolInvocation { return { name, args: [], input, execute, redactRawAfterParse: true }; }
export async function writeList(dir: string, relPath: string, lines: string[]) { const p = join(dir, relPath); await mkdir(dirname(p), { recursive: true }); await writeFile(p, lines.join("\n") + "\n"); return p; }
export async function runToolBatch(dir: string, phase: number, tools: ToolInvocation[], concurrency: number, requestsPerSecond = 1): Promise<ToolRunResult[]> { await mkdir(join(dir, "outputs", `phase-${phase}`), { recursive: true }); const results: ToolRunResult[] = []; let next = 0; let lastStart = 0; const minGap = Math.max(0, 1000 / Math.max(1, requestsPerSecond)); async function takeStartSlot() { const now = Date.now(); const wait = Math.max(0, lastStart + minGap - now); if (wait) await new Promise((r) => setTimeout(r, wait)); lastStart = Date.now(); } async function worker() { for (;;) { const i = next++; if (i >= tools.length) return; await takeStartSlot(); results[i] = await runTool(dir, phase, tools[i]); } } await Promise.all(Array.from({ length: Math.max(1, Math.min(concurrency, tools.length)) }, worker)); return results; }
async function runTool(dir: string, phase: number, spec: ToolInvocation): Promise<ToolRunResult> {
  const stamp = new Date().toISOString().replace(/[:.]/g, ""); const outDir = join(dir, "outputs", `phase-${phase}`, `${spec.name}-${stamp}-${randomBytes(2).toString("hex")}`); await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, "command.json"), JSON.stringify({ tool: spec.name, command: spec.command ?? (spec.execute ? "typescript" : undefined), args: spec.args, input: spec.input, timeout_ms: spec.timeoutMs ?? 120000, max_retries: 3 }, null, 2));
  if (spec.execute) { const started = Date.now(); const exec = await spec.execute(); const result: any = exec.result ?? spec.parser?.(exec.stdout ?? "", exec.stderr ?? "", exec.code ?? 0) ?? {}; const blocked = String(result?.status ?? "").startsWith("BLOCKED"); await writeStructured(outDir, "<raw deleted after normalized parsing>", "<raw deleted after normalized parsing>", { code: exec.code ?? (blocked ? 2 : 0), signal: null, duration_ms: Date.now() - started, attempts: 1, executor: "typescript" }, result); return { tool: spec.name, success: !blocked && (exec.code ?? 0) === 0, missing: blocked, outDir, summary: summarize(result, { code: exec.code ?? (blocked ? 2 : 0), stderr: exec.stderr ?? "" }), result, rawRetained: false }; }
  if (!spec.command) { const result: any = spec.parser?.("", "", 0) ?? {}; const blocked = String(result?.status ?? "").startsWith("BLOCKED"); await writeStructured(outDir, "", "", { code: blocked ? 2 : 0, signal: null, duration_ms: 0, attempts: 1 }, result); return { tool: spec.name, success: !blocked, missing: blocked, outDir, summary: blocked ? String(result.status) : "structured wrapper recorded", result, rawRetained: false }; }
  if (spec.requiredBinary && !(await commandExists(spec.requiredBinary))) { const msg = `Missing required tool: ${spec.requiredBinary}`; await writeStructured(outDir, "", msg, { code: 127, signal: null, duration_ms: 0, attempts: 0 }, { error: { code: "MISSING_TOOL", message: msg, retryable: false } }); return { tool: spec.name, success: false, missing: true, outDir, summary: msg, result: null, rawRetained: false }; }
  const started = Date.now(); let exec: Awaited<ReturnType<typeof spawnCapture>> = { stdout: "", stderr: "", code: 1, signal: null }; let attempts = 0;
  for (; attempts < 3; attempts++) { exec = await spawnCapture(spec.command, spec.args, spec.timeoutMs ?? 120000); if (exec.code === 0 || exec.code === 127) break; await new Promise((r) => setTimeout(r, 250 * (attempts + 1))); }
  const result = spec.parser?.(exec.stdout, exec.stderr, exec.code) ?? { stdout: exec.stdout.slice(0, 10000) };
  await writeStructured(outDir, "<raw deleted after normalized parsing>", "<raw deleted after normalized parsing>", { code: exec.code, signal: exec.signal, duration_ms: Date.now() - started, attempts }, result);
  return { tool: spec.name, success: exec.code === 0, missing: false, outDir, summary: summarize(result, exec), result, rawRetained: false };
}
async function writeStructured(outDir: string, stdout: string, stderr: string, exit: unknown, result: unknown) { await writeFile(join(outDir, "stdout.txt"), redact(stdout)); await writeFile(join(outDir, "stderr.txt"), redact(stderr)); await writeFile(join(outDir, "exit.json"), JSON.stringify(exit, null, 2)); await writeFile(join(outDir, "result.json"), JSON.stringify(result, null, 2)); }
function spawnCapture(command: string, args: string[], timeoutMs: number): Promise<{ stdout: string; stderr: string; code: number | null; signal: NodeJS.Signals | null }> { return new Promise((resolve) => { const child = spawn(command, args, { stdio: ["ignore", "pipe", "pipe"] }); let stdout = "", stderr = ""; const timer = setTimeout(() => child.kill("SIGTERM"), timeoutMs); child.stdout.on("data", (d) => stdout += d.toString()); child.stderr.on("data", (d) => stderr += d.toString()); child.on("error", (e) => { clearTimeout(timer); resolve({ stdout, stderr: stderr + String(e), code: 127, signal: null }); }); child.on("close", (code, signal) => { clearTimeout(timer); resolve({ stdout, stderr, code, signal }); }); }); }
async function commandExists(command: string) { if (command.includes("/")) return existsSync(command); return (process.env.PATH ?? "").split(":").some((p) => existsSync(join(p, command))); }
function summarize(result: any, exec: { code: number | null; stderr: string }) { if (exec.code !== 0) return `exit ${exec.code}: ${exec.stderr.slice(0, 180)}`; if (Array.isArray(result?.subdomains)) return `${result.subdomains.length} subdomains`; if (Array.isArray(result?.items)) return `${result.items.length} JSONL items`; if (Array.isArray(result?.lines)) return `${result.lines.length} lines`; return "completed"; }
