export type Severity = "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type PhaseStatus = "pending" | "running" | "COMPLETE" | "COMPLETE_WITH_WARNINGS" | "BLOCKED_MISSING_TOOLS" | "SKIPPED_BY_ROE" | "BLOCKED_DEPENDENCY_PHASE_N" | "BLOCKED_MISSING_SECRET" | "BLOCKED_MISSING_PEER_ACCOUNTS" | "FAILED";
export type AllowedAction = "passive_recon" | "active_recon" | "authenticated_testing" | "vulnerability_scanning" | "injection_testing" | "cloud_testing" | "third_party_testing" | "rate_limit_testing";
export const ALLOWED_ACTIONS: AllowedAction[] = ["passive_recon","active_recon","authenticated_testing","vulnerability_scanning","injection_testing","cloud_testing","third_party_testing","rate_limit_testing"];
export const ACCOUNT_ROLES = ["standard", "admin", "free", "paid"] as const;
export interface AccountSpec { username?: string; secret_ref?: string; role: "standard" | "admin" | "free" | "paid"; }
export interface RoeSpec { assessment_name: string; targets: { domains: string[] }; exclusions: { domains: string[]; paths: string[] }; accounts: Record<string, AccountSpec>; allowed_actions: AllowedAction[]; rate_limits: { requests_per_second: number; concurrent_hosts: number }; }
export interface Finding { id: string; title: string; severity: Severity; category: string; affected: string[]; impact: string; evidence: string[]; reproduction: string[]; remediation: string; references: string[]; created_at: string; redaction_notes?: string; }
export interface SessionState { session_id: string; created_at: string; roe_source_path: string; roe_sha256: string; status: "initialized" | "running" | "complete" | "failed"; current_phase?: number; phases: Record<string, { status: PhaseStatus; updated_at?: string; notes?: string[]; coverage?: Record<string, unknown> }>; output_index: OutputIndexEntry[]; findings_index: string[]; candidates: CandidateTarget[]; coverage: Record<string, unknown>; }
export interface CandidateTarget { host: string; source: string; reason: string; approved: boolean; discovered_at: string; }
export interface OutputIndexEntry { phase: number; tool: string; dir: string; success: boolean; summary: string; raw_retained: boolean; }
export interface ToolInvocation { name: string; args: string[]; input: Record<string, unknown>; command?: string; timeoutMs?: number; requiredBinary?: string; parser?: (stdout: string, stderr: string, exitCode: number | null) => unknown; redactRawAfterParse?: boolean; execute?: () => Promise<{ stdout?: string; stderr?: string; code?: number; result?: unknown }>; }
export interface ToolRunResult { tool: string; success: boolean; missing: boolean; outDir: string; summary: string; result: any; rawRetained: boolean; }
export interface PhaseDef { id: number; name: string; requiredAction?: AllowedAction; dependencies: number[]; accountRequirement: "none" | ">=1" | ">=2-standard" | "phase-specific"; skill: string; steps: string[]; plan: (roe: RoeSpec, session: SessionState, sessionDir: string) => Promise<ToolInvocation[]>; }
