import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { isAbsolute, join, resolve } from "node:path";
import { initDirs, appendWork, loadSession, saveSession, sessionDir, verifyRoeHash } from "./lib/session_state";
import { parseSimpleYaml, serializeRoe, sha256, validateRoe } from "./lib/roe";
import { PHASES } from "./lib/planner";
import { runPhaseLoop } from "./lib/action_loop";
import { generateReport } from "./lib/report";
import { SessionState } from "./lib/types";

type Notify = (message: string, level?: "info" | "error" | "warning" | "success") => void;
export default function registerRedteam(pi: ExtensionAPI) {
  pi.on("resources_discover", async (event) => { const skillDir = join(event.cwd, "skills", "redteam"); if (existsSync(skillDir)) return { skillPaths: [skillDir] }; });
  pi.registerCommand("redteam", { description: "Agentic VAPT workflow: init, phase, auto, resume, status, report", handler: async (args, ctx) => { try { const parts = splitArgs(args.trim()); const sub = parts.shift(); if (!sub) return usage(ctx.ui.notify.bind(ctx.ui)); if (sub === "init") return init(parts, ctx.cwd, ctx.ui.notify.bind(ctx.ui)); if (sub === "phase") return phase(parts, ctx.ui.notify.bind(ctx.ui), ctx); if (sub === "auto") return auto(parts, ctx.ui.notify.bind(ctx.ui), ctx); if (sub === "resume") return resume(parts, ctx.ui.notify.bind(ctx.ui)); if (sub === "approve") return approve(parts, ctx.ui.notify.bind(ctx.ui)); if (sub === "status") return status(parts, ctx.ui.notify.bind(ctx.ui)); if (sub === "report") return report(parts, ctx.cwd, ctx.ui.notify.bind(ctx.ui), ctx); return usage(ctx.ui.notify.bind(ctx.ui)); } catch (e) { ctx.ui.notify(`redteam error: ${e instanceof Error ? e.message : String(e)}`, "error"); } } });
}
function usage(notify: Notify) { notify("Usage: /redteam init ./roe.yml | phase <session_id> <1-14> | auto <session_id> | resume <session_id> | approve <session_id> <host> | status <session_id> | report <session_id> --output report.md", "info"); }
async function init(parts: string[], cwd: string, notify: Notify) { const arg = parts[0]; if (!arg) return usage(notify); const sourcePath = isAbsolute(arg) ? arg : resolve(cwd, arg); const roe = validateRoe(parseSimpleYaml(await readFile(sourcePath, "utf8"))); const normalized = serializeRoe(roe); const created = new Date().toISOString(); const id = `${created.replace(/[:.]/g, "").replace(/-/g, "")}-${randomBytes(4).toString("hex")}`; const dir = sessionDir(id); await initDirs(dir); await writeFile(join(dir, "roe.yml"), normalized, { flag: "wx" }); await writeFile(join(dir, "roe.sha256"), `${sha256(normalized)}\n`, { flag: "wx" }); const session: SessionState = { session_id: id, created_at: created, roe_source_path: sourcePath, roe_sha256: sha256(normalized), status: "initialized", phases: Object.fromEntries(PHASES.map((p) => [String(p.id), { status: "pending" }])), output_index: [], findings_index: [], candidates: [], coverage: {} }; await saveSession(dir, session); await appendWork(dir, `# Red Team Session: ${id}\nStarted: ${created}\nAssessment: ${roe.assessment_name}\nRoE YAML: roe.yml\nRoE SHA256: ${session.roe_sha256}\n\n## ${created} — Session initialized\n- Source RoE: ${sourcePath}\n- Targets: ${roe.targets.domains.join(", ")}\n- Allowed actions: ${roe.allowed_actions.join(", ")}\n- Network activity: none; initialization only\n`); notify(`Red team session initialized: ${id}\nNext: /redteam phase ${id} 1 or /redteam auto ${id}`, "info"); }
async function phase(parts: string[], notify: Notify, llmCtx?: any) { const [id, p] = parts; const phaseId = Number(p); if (!id || !Number.isInteger(phaseId)) return usage(notify); notify(await runOne(id, phaseId, llmCtx), "info"); }
async function auto(parts: string[], notify: Notify, llmCtx?: any) { const id = parts[0]; if (!id) return usage(notify); const lines: string[] = []; for (const p of PHASES) { const line = await runOne(id, p.id, llmCtx); lines.push(line); if (/FAILED|BLOCKED_MISSING_SECRET/.test(line)) break; } notify(lines.join("\n"), "info"); }
async function runOne(id: string, phaseId: number, llmCtx?: any) { const dir = sessionDir(id); const session = await loadSession(dir); await verifyRoeHash(dir, session); const roe = validateRoe(parseSimpleYaml(await readFile(join(dir, "roe.yml"), "utf8"))); const phase = PHASES.find((p) => p.id === phaseId); if (!phase) return `Unknown phase: ${phaseId}`; return runPhaseLoop(dir, roe, session, phase, llmCtx); }
async function resume(parts: string[], notify: Notify) { const id = parts[0]; if (!id) return usage(notify); const dir = sessionDir(id); const s = await loadSession(dir); await verifyRoeHash(dir, s); const next = PHASES.find((p) => s.phases[String(p.id)]?.status === "pending"); await appendWork(dir, `\n## ${new Date().toISOString()} — Session resumed\n- Next phase: ${next ? `${next.id} ${next.name}` : "none"}\n`); notify(next ? `Resume ready. Next: /redteam phase ${id} ${next.id}` : "All phases have terminal statuses.", "info"); }
async function approve(parts: string[], notify: Notify) { const [id, host] = parts; if (!id || !host) return usage(notify); const dir = sessionDir(id); const s = await loadSession(dir); const c = s.candidates.find((x) => x.host === host.toLowerCase()); if (!c) return notify(`Candidate not found: ${host}`, "error"); c.approved = true; await saveSession(dir, s); await appendWork(dir, `\n## ${new Date().toISOString()} — Candidate approved\n- Host: ${c.host}\n- Source: ${c.source}\n`); notify(`Approved candidate for future planning: ${c.host}`, "success"); }
async function status(parts: string[], notify: Notify) { const id = parts[0]; if (!id) return usage(notify); const s = await loadSession(sessionDir(id)); notify(`Session ${id}: ${s.status}\n${PHASES.map((p) => `${p.id}. ${p.name}: ${s.phases[String(p.id)]?.status ?? "unknown"}`).join("\n")}\nCandidates pending approval: ${s.candidates.filter((c) => !c.approved).length}`, "info"); }
async function report(parts: string[], cwd: string, notify: Notify, llmCtx?: any) { const id = parts[0]; if (!id) return usage(notify); const flag = parts.indexOf("--output"); const output = flag >= 0 && parts[flag + 1] ? (isAbsolute(parts[flag + 1]) ? parts[flag + 1] : resolve(cwd, parts[flag + 1])) : undefined; const dir = sessionDir(id); const s = await loadSession(dir); await verifyRoeHash(dir, s); const roe = validateRoe(parseSimpleYaml(await readFile(join(dir, "roe.yml"), "utf8"))); const path = await generateReport(dir, roe, s, output, llmCtx); notify(`Report written: ${path}`, "info"); }
function splitArgs(s: string) { return s.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)?.map((x) => x.replace(/^['"]|['"]$/g, "")) ?? []; }
